[package]
name = "sensor-dashboard"
version = "1.0.0"
edition = "2018"
authors = ["Arne Keller <arne.keller@posteo.de>"]
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"
